[package]
name = "thrush"
description = "The bootstrap compiler for the Thrush Programming language."
version = "1.0.0"
edition = "2021"

[dependencies]
ahash = "0.8.11"
chrono = "0.4.38"
colored = "2.1.0"
llvmenv = "0.3.2"
llvm-sys = "170.1.1"
inkwell = { version = "0.5.0", features = ["llvm17-0"] }

